DROP TABLE IF EXISTS livros;

CREATE TABLE livros (
    ID_LIVRO INT PRIMARY KEY,
    TITULO_LIVRO VARCHAR(100),
    AUTOR_LIVRO VARCHAR(100),
    ANO_LIVRO INT,
    GENERO_LIVRO VARCHAR(255),
    DISPONIVEL BOOLEAN
);


INSERT INTO livros (ID_LIVRO, TITULO_LIVRO, AUTOR_LIVRO, ANO_LIVRO, GENERO_LIVRO, DISPONIVEL)
VALUES (1, 'Dom Casmurro', 'Machado de Assis', 1899, 'Romance', FALSE);

INSERT INTO livros (ID_LIVRO, TITULO_LIVRO, AUTOR_LIVRO, ANO_LIVRO, GENERO_LIVRO, DISPONIVEL)
VALUES (2, '1984', 'George Orwell', 1949, 'Ficção Científica', TRUE);

INSERT INTO livros (ID_LIVRO, TITULO_LIVRO, AUTOR_LIVRO, ANO_LIVRO, GENERO_LIVRO, DISPONIVEL)
VALUES (3, 'Harry Potter e a Pedra Filosofal', 'J.K. Rowling', 1997, 'Fantasia', FALSE);

INSERT INTO livros (ID_LIVRO, TITULO_LIVRO, AUTOR_LIVRO, ANO_LIVRO, GENERO_LIVRO, DISPONIVEL)
VALUES (4, 'O Senhor dos Anéis: A Sociedade do Anel', 'J.R.R. Tolkien', 1954, 'Fantasia', TRUE);

INSERT INTO livros (ID_LIVRO, TITULO_LIVRO, AUTOR_LIVRO, ANO_LIVRO, GENERO_LIVRO, DISPONIVEL)
VALUES (5, 'A Menina que Roubava Livros', 'Markus Zusak', 2005, 'Drama', TRUE);

SELECT * FROM livros;

UPDATE livros SET DISPONIVEL = FALSE WHERE ID_LIVRO = 5;

SELECT * FROM livros;

SELECT * FROM livros ORDER BY ANO_LIVRO DESC;

DELETE FROM livros WHERE ANO_LIVRO<1940;

SELECT * FROM livros ORDER BY ANO_LIVRO DESC;

DROP TABLE livros;

CREATE TABLE livros (
    ID_LIVRO INT PRIMARY KEY,
    TITULO_LIVRO VARCHAR(100),
    AUTOR_LIVRO VARCHAR(100),
    ANO_LIVRO INT,
    GENERO_LIVRO VARCHAR(255),
    DISPONIVEL BOOLEAN
);

SELECT * FROM livros;
